### ISSUE TITLE
Reddit function is stupid

### ISSUE THREAD

**Issue by cbirkett** [jinpark/common-bot#10]
![screen shot 2014-04-15 at 4 51 21 pm](https://cloud.githubusercontent.com/assets/1205854/2712952/eb37473e-c4df-11e3-836d-ec47597a1eeb.png)

**Comment by jinpark** [comment]
Thanks @cbirkett I'll go fix that.

**Comment by jinpark** [comment]
Fixed. Marked for retest. @cbirkett Please retest :D
