### ISSUE TITLE
.title does not work

### ISSUE THREAD

**Issue by cbirkett** [jinpark/common-bot#13]

**Comment by cbirkett** [comment]
18:59:31 <common> http://xkcd.com/1037 [Umwelt]
18:59:47 <&jin> you having fun bob?
18:59:53 <~cbirkett> .title
18:59:56 <~cbirkett> DOES NOT WORK

**Comment by jinpark** [comment]
You know you can edit your original post

**Comment by cbirkett** [comment]
That is not an issue.
