### ISSUE TITLE
.tr no help and no switches

### ISSUE THREAD

**Issue by vertigoacid** [jinpark/common-bot#14]
.help tr
<no output>
and it is unclear how to pass ISO 639-1 codes as an argument to specify the languages desired

**Comment by jinpark** [comment]
Yea this is going to be high priority.

**Comment by jinpark** [comment]
Try it out now plz

```
[00:08:19]  <&jin>   .tr hello -en -es
[00:08:20]  <common>     jin: "¡hola" (en to es, translate.google.com)
```

**Comment by jinpark** [comment]
no one uses this :(
