### ISSUE TITLE
.ud enhancement

### ISSUE THREAD

**Issue by vertigoacid** [jinpark/common-bot#18]
# Feature requests
1. Add argument to .ud to allow printing of additional definitions below the top one. Useful for when the first definition sucks ass.

Current behavior:
18:53 <&vertigo> .ud khlav kalash
18:53 <common> Khlav Kalash: A recipe of mutton, lamb, tomatoes, carnations,
               onions, water, oil, and salt & pepper. It's all ground into a
               thick ball of meat.  Best served on a stick, with Mountain Dew
               or Crab Juice - as seen on The Simpsons.

Desired behavior
.ud -2 khlav kalash

<common> Khlav Kalash: A supposed awful tasting item from your run of the mill foreign lunch vendor located in downtown New York City. This is the actual spelling of the food, as opposed to the otherwise used Khlav K(h)alash. From past experiences with the Khlav Kalash, the main choice of beverage is typically a can or two of Crab Juice. This item is served ONLY only a stick, no bowl. 
"No Pizza, Only Khlav Kalash"
1. As a general enhancement, it would be useful to have a command to ask common to continue printing past the irc line length limit. Alternatively, this may be something we can achieve w/ u-lining common, as I believe that removes the limit, but if not, then this could be good:

Current behavior:
18:58 <&vertigo> .ud peef
18:58 <common> Peef: A peef is a penis fart, similar to a queef. A queef is to
               a female as a peef is to a male.  There have been very few
               recorded incidences of peefs. However, we do know that a peef is
               both pleasant and painful for the 'peefer'. No incidences of a
               'wet peef' have ever been recorded.  On a related note, the peef
               has much militaristic potential. Theoretically, with the proper
               enhancements and adjustments, the peef could become powerful
               enough to repla

Desired behavior:

18:58 <&vertigo> .ud peef
18:58 <common> Peef: A peef is a penis fart, similar to a queef. A queef is to
               a female as a peef is to a male.  There have been very few
               recorded incidences of peefs. However, we do know that a peef is
               both pleasant and painful for the 'peefer'. No incidences of a
               'wet peef' have ever been recorded.  On a related note, the peef
               has much militaristic potential. Theoretically, with the proper
               enhancements and adjustments, the peef could become powerful
               enough to repla
<vertigo>.GoOn
<common> replace nuclear warfare.

---

EDIT: going to make checklist
- [ ] Additional Definitions
- [ ] Remove limit for max length

**Comment by vertigoacid** [comment]
I don't know why github won't respect my numbering of 2. up there, but, I swear I'm not a retard and didn't put 1. twice

**Comment by jinpark** [comment]
lol .GoOn

**Comment by jinpark** [comment]
@vertigoacid how is 

```
.ud cat -def 2
```

or something liek taht instead of just the number for futureproofing. Also how is the user going to know how many definitions there are. Should that be added to the original `.ud cat` thing?

**Comment by jinpark** [comment]
closing since it seems to work :P
