### ISSUE TITLE
FR: Several new last.fm commands

### ISSUE THREAD

**Issue by jwhxb2** [jinpark/common-bot#19]
In order of priority:
1. Rework the .lastfm command to take options to display different kinds of info and perform other last.fm related actions. These options should be a hyphen followed by a single lowercase letter, e.g. "-t" and should be specified after the .lastfm command and sometimes a last.fm username in a manner similar to:

.lastfm [last.fm username, uses linked name if omitted] -t [option-specific arguments go here]
1. Add an option "-l" to .lastfm for linking IRC nicks to last.fm usernames to make using the other last.fm commands easier. If for any other last.fm command that takes a last.fm username as an argument, no username is specified, common will use the last.fm username linked to the nick of the person who sent the command. If no username is linked, it will display the message it does currently. Multiple nicks should be allowed to link to the same user.

Usage:
[One argument: links specified username to sender]
<user> .lastfm [last.fm username] -l
[Two arguments: Links specified username to specified nick]
<user> .lastfm [last.fm username] -l [nick]

Desired behavior: 

<Cerpin> .lastfm Z_LAMP -l Bouncing_Bread
[links to nick of person who sent the command]
<common>  User "Z_LAMP" linked to Bouncing_Bread.

<Cerpin> .lastfm Z_LAMP -l
[links to nick of sender]
<common> User "Z_LAMP" linked to Cerpin.

<Cerpin> .lastfm
<common> Last played Don't Be Afraid, You Have Just Got Your Eyes Closed by múm from the album Finally We Are No One - http://www.last.fm/music/m%C3%BAm/_/Don%27t+Be+Afraid,+You+Have+Just+Got+Your+Eyes+Closed
1. Add an option "-t" to display top 10 artists or songs over a specified interval. -t takes 3 arguments: the type of content to display (artists or tracks. maybe albums too, though that might require more work), the denomination of time the interval will be specified in(d [days], w [weeks], m [months] etc. ), and the interval itself (a numeric value). If no interval is specified, the command will use overall stats.

Usage:
.lastfm [username] -t [content type] [interval type] [interval]

Desired behavior:

<Cerpin> .lastfm -t artists m 1
<common> Your top 10 played artists for the past 1 month are: Brainiac (38 plays), múm (32 plays), Fluxion (23 plays), Main (19 plays), U.S. Maple (18 plays), NUMBER GIRL (16 plays), Mika Vainio (15 plays), bvdub (15 plays), Throbbing Gristle (14 plays), Sympathy Nervous (10 plays).

<Cerpin> .lastfm haste -t tracks
<common> Your top 10 played tracks are: MONORAL – kiri (517 plays) [.....]

**Comment by jinpark** [comment]
Whooo. thanks for the detailed report mr cerpin

**Comment by jinpark** [comment]
```
<Cerpin> .lastfm Z_LAMP -l Bouncing_Bread
```

Not sure if you meant to put `Bouncing_Bread` there. It'll just link your irc username to whatever whatever you give it past the -l ex. ```<Cerpin> .lastfm -l Z_LAMP ''' will link irc username cerpin to z_lamp

```
Add an option "-t" to display top 10 artists or songs over a specified interval. -t takes 3 arguments: the type of content to display (artists or tracks. maybe albums too, though that might require more work), the denomination of time the interval will be specified in(d [days], w [weeks], m [months] etc. ), and the interval itself (a numeric value). If no interval is specified, the command will use overall stats.
Usage:
.lastfm [username] -t [content type] [interval type] [interval]
```

Not sure if this is worth doing? Doesn't seem like a real need :P Maybe just link to the url for the lastfm user?

**Comment by jwhxb2** [comment]
.lastfm Z_LAMP -l would do the last thing you said, and the argument after -l is supposed to be if you want to specify a link other than your own to link

**Comment by jinpark** [comment]
making a list for myself
- [x] ability to link nicks
- [x] ability to use nicks instead of lastfm usernames if they exist (cerpin says doesnt matter so not doing it)
- [ ] After they're both done, create new issue for the -t thing

**Comment by jinpark** [comment]
@Cerpin 
try

```
.userinfo --lastfm z_lamp
```

Decided to make it a separate command so I can add things to it later and not make it lastfm specific and just make it userinfo specific.

**Comment by jinpark** [comment]
So I'm too lazy to do the month stuff for now.

**Comment by jinpark** [comment]
Closing this and will open new issue with just the time lastfm thingy
