### ISSUE TITLE
UTF-8 input

### ISSUE THREAD

**Issue by vertigoacid** [jinpark/common-bot#4]
seems to work okay on output but not on input

**Comment by jinpark** [comment]
![image](https://cloud.githubusercontent.com/assets/1847812/2687318/610fc3dc-c24c-11e3-9778-dbdaa826ecc3.png)
Please, sir, I want some more (information)

EDIT:
I fixed UD and wea for handing unicode. Not sure what else needs it

**Comment by jinpark** [comment]
@vertigoacid said this is good

**Comment by jooize** [comment]
```
07:34:12     jewice │ .w åkerbär
07:34:12     common │ UnicodeEncodeError: 'ascii' codec can't encode character
u'\xe5' in position 0: ordinal not in range(128) (file
"/usr/lib/python2.7/urllib.py", line 1312, in urlencode)
```
