### ISSUE TITLE
farenheit

### ISSUE THREAD

**Issue by uncola** [jinpark/common-bot#8]
FARENHEIT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

EDIT by @jinpark:
uncola wants F for weather. Also fix spellingz plz

**Comment by jinpark** [comment]
Closing until someone else complains about it
