### ISSUE TITLE
encoding issue in URLs from google

### ISSUE THREAD

**Issue by vertigoacid** [jinpark/common-bot#9]
example:
21:42 <&vertigo> .g how much does snorlax weigh
21:42 <common> http://bulbapedia.bulbagarden.net/wiki/Snorlax_(Pok%25C3%25A9mon) - Snorlax (Pokémon) - Bulbapedia - Bulbagarden

whereas the correct link is:
http://bulbapedia.bulbagarden.net/wiki/Snorlax_(Pok%C3%A9mon)

**Comment by jinpark** [comment]
@vertigoacid retest please!

**Comment by cbirkett** [comment]
![screen shot 2014-04-15 at 9 41 01 pm](https://cloud.githubusercontent.com/assets/1205854/2715273/3bba4f58-c508-11e3-9ef6-12c69e4e93c4.png)
